doc: inclusão conteúdo link
animaliads/animalia-web-components pull request #13
Opened 2021-06-15 20:29 UTC by edioli

Inclusão da documentação do componente link, nas seções:
- Visão geral
- Boas práticas (faça/ não faça, acessibilidade)
- Propriedades customizáveis

2021-06-16 17:02 UTC, taisertltotvs reviewed
Muito massa Di. Só encontrei dois pontos, sobre a imagem dos estados vir depois, como já tinha comentado ctg. E o link para as propriedades customizáveis, que fica na seção de anatomia, não esta funcionando certo para mim, leva para as boas práticas.

2021-06-16 18:50 UTC, nicoleoliveira requested changes

2021-06-16 18:50 UTC, nicoleoliveira commented
> Muito massa Di. Só encontrei dois pontos, sobre a imagem dos estados vir depois, como já tinha comentado ctg. E o link para as propriedades customizáveis, que fica na seção de anatomia, não esta funcionando certo para mim, leva para as boas práticas.

Eu testei localmente e está funcionando aqui :) deve ser alguma coisa do ambiente do Chromatic
@edioli  e @taisertltotvs

2021-06-16 19:51 UTC, edioli commented on packages/link/src/stories/best-practices.mdx
> +import link_dont_4 from './img/link-naofazer-4.jpg';
Alterado!

2021-06-17 14:24 UTC, edioli commented on packages/link/src/stories/custom-properties.mdx
> +| `--text-color-visited`    | cor da label no estado visited     | $color-action-pressed |
Ficou alinhado que iremos revisar a representação de tokens na migração da documentação.

2021-06-17 14:29 UTC, nicoleoliveira approved these changes

2021-06-17 14:41 UTC, taisertltotvs approved these changes

2021-06-17 14:52 UTC, merged

2021-06-17 17:20 UTC, peixeh commented
Verificado, os pontos que ficaram foram somente esses:
• em "boas práticas / visual / não fazer / ...contraste, não...": falta um espaço entre a vírgula e a palavra "não".
• em "propriedades customizáveis / coluna descrição / família tipográfica...": faltou acento no "tipográfica".