feat(button): novo componente
animaliads/animalia-web-components pull request #14
Opened 2021-06-16 13:30 UTC by nicoleoliveira

### Implementação do componente button com as suas variações

- primary
- secondary
- danger
- tertiary

### Revisão:
**designers:**
Validar utilizando o storyook no chromatic

**devs:**
- pode utilizar o ambiente de demo anexado, baixar e executar em um servidor local, como o live-server.
[demo.zip](https://github.com/animaliads/animalia-web-components/files/6663356/demo.zip)
- testar utilizando o stackblitzs (tem exemplo dentro do chromatic nas actions do github)
- testar utilizando o chromatic
- PO UI: tem uma [branch no PO UI](https://github.com/po-ui/po-angular/tree/animalia-poc-button) com a implementação do button para testes

Na aprovação, aprovar também as PRs:
-

2021-06-16 17:43 UTC, marcelobotega commented on packages/button/src/enums/button-kind.enum.ts
> +export enum ButtonKind {
```suggestion
export enum ButtonKind {
```
```suggestion
export enum ButtonKind {
```

2021-06-16 18:10 UTC, taisertltotvs approved these changes
Tudo certo no storybook, no safari também esta funcionando.

2021-06-16 18:31 UTC, marcelobotega requested changes

2021-06-16 18:31 UTC, marcelobotega commented on packages/button/src/enums/button-kind.enum.ts
> +}
Com relação ao kind, não seria melhor usar algo que faca referencia ao estilo do botão ?
Penso que seria mais fácil relacionar o kind ao estilo do botão, ja que se continuar com essa nomenclatura e por ventura tivermos mais tipos de kind teríamos um quaternary, quinary, senary etc e esses nomes não fazem referencia a nada e acabaria dificultando a vida do usuário.
Podemos pegar o angular material de exemplo (https://material.angular.io/components/button/overview) os botoes tem nomenclatura com base no estilo dele, onde o primary seria flat, secondary seria stroked e o tertiary seria basic. O bootstrap também trabalha de forma similar.

2021-06-16 18:31 UTC, marcelobotega commented on packages/button/src/button.ts
> +  get danger(): string {
Pensando no futuro não poderia acontecer de o botão ter mais estados ? 
Seguindo o danger poderíamos ter algo no estilo de caution, info, success etc sera que no lugar de um boolean não seria melhor já ter um enum (ou literal type) com o estado do botão  ?

2021-06-16 19:20 UTC, edioli commented
**Dúvida:** No botão secundário, as propriedades de box-shadow, background-color e border-style, aparecem, mesmo não sendo customizáveis?
<img width="426" alt="Captura de Tela 2021-06-16 às 16 16 29" src="https://user-images.githubusercontent.com/75502935/122279517-824b1980-cebe-11eb-9895-6509352f57c8.png">

2021-06-16 19:37 UTC, edioli commented
Por não ter o "tertiary danger", daria para não disponibilizar o danger nessa variação do botão?

2021-06-16 20:03 UTC, taisertltotvs commented on packages/button/src/enums/button-kind.enum.ts
> +}
Sobre este item, fizemos algumas pesquisas e descobertas para chegar aos tipos de botões que teríamos no design system. E com isso adotamos esta nomenclatura para facilitar o entendimento do usuário sobre qual botão utilizar em cada situação, de acordo com a prioridade. Pois utilizando o nome do estilo não temos direcionamento de hierarquia. Na documentação explicamos melhor essas hierarquias e quando usar cada um.

2021-06-16 20:05 UTC, taisertltotvs commented on packages/button/src/button.ts
> +  get danger(): string {
Nessa caso também optamos por não ter outros estados além do danger e disable, pois de acordo com os levantamentos que fizemos nos produtos da TOTVS, eles não estavam sendo utilizados nas interfaces.

2021-06-16 20:06 UTC, marcelobotega commented on packages/button/src/enums/button-kind.enum.ts
> +}
agora faz sentido a nomenclatura xD

2021-06-16 20:07 UTC, taisertltotvs commented on packages/button/src/enums/button-kind.enum.ts
> +}
Uma coisa que podemos trazer para os próximos PRs são algumas definições para vcs saberem também ;)

2021-06-16 20:09 UTC, marcelobotega commented on packages/button/src/enums/button-kind.enum.ts
> +}
Seria legal, pois como não estamos diretamente envolvidos podemos ficar sem o contexto das decisões xD

2021-06-16 20:10 UTC, marcelobotega approved these changes

2021-06-16 20:10 UTC, taisertltotvs commented on packages/button/src/enums/button-kind.enum.ts
> +}
Combinado!

2021-06-17 13:26 UTC, nicoleoliveira commented on packages/button/src/enums/button-type.enum.ts
> +}
Oi, eu fiz o teste aqui, mas daí para esse caso precisa ser um enum mesmo, porque tem outro trecho do código que ele faz uma comparação com o valor default :/ 
Nós próximas releases, nós iremos criar alguns decorators para as propriedades dos componentes, dai vou avaliar se tem como incluir os types. O que acha?

2021-06-17 13:37 UTC, nicoleoliveira commented
> No botão secundário e terciário, as propriedades de box-shadow, background-color e de border, ficam visíveis, mesmo não sendo customizáveis?
> <img alt="Captura de Tela 2021-06-16 às 16 16 29" width="400" src="https://user-images.githubusercontent.com/75502935/122279517-824b1980-cebe-11eb-9895-6509352f57c8.png">
> 
> <img alt="Captura de Tela 2021-06-16 às 16 21 53" width="400" src="https://user-images.githubusercontent.com/75502935/122279965-07363300-cebf-11eb-99f0-118945349a39.png">

Na inspeção de elemento do navegador sim, não temos como impedir isso, faz parte da tecnologia css que utilizamos :)

2021-06-17 14:03 UTC, marcelobotega commented on packages/button/src/enums/button-type.enum.ts
> +}
Para comparar e só usar como string tipo assim:
```typescript
  const btnType: ButtonType = 'reset';
  
  if (btnType === 'submit') {
  }
```

Mas não precisa ser feito agora, o comentário foi mais para disseminar o conhecimento sobre literal types mesmo e no futuro ser analisado o uso deles =)

2021-06-17 14:04 UTC, marcelobotega approved these changes

2021-06-17 14:09 UTC, edioli approved these changes

2021-06-17 14:09 UTC, nicoleoliveira commented
> Por não ter o "tertiary danger", daria para não disponibilizar o danger nessa variação do botão?

Tem um tratamento interno para isso não acontecer :) e adicionamos na documentação para o desenvolvedor saber.

2021-06-17 14:14 UTC, merged