doc: inclusão do conteúdo dos botões
animaliads/animalia-web-components pull request #15
Opened 2021-06-17 12:55 UTC by taisertltotvs

2021-06-17 13:39 UTC, peixeh commented
@taisertltotvs
Bela documentação! Dei uma olhada por cima na doc (nem conte como validação pfv) e peguei dois pontos: 

• Em Botão / Desenvolvimento / Como utilizar / <ani-button>Hello world!<ani-button></ani-button></ani-button>: o texto está duplicado;
• Os exemplos com focus dos botões estão diferentes dos que estamos usando no Zeplin.

2021-06-17 14:23 UTC, milkatx reviewed
Só vi esse ponto em Botão >Desenvolvimento >Como utilizar>Hello world!: o <ani-button></ani-button> está duplicado, fora isso tudo ok.

2021-06-17 16:51 UTC, nicoleoliveira commented
> @taisertltotvs
> Bela documentação! Dei uma olhada por cima na doc (nem conte como validação pfv) e peguei dois pontos:
> 
> • Em Botão / Desenvolvimento / Como utilizar / Hello world!: o texto está duplicado;
> • Os exemplos com focus dos botões estão diferentes dos que estamos usando no Zeplin.

A parte da documentação de desenvolvimento já foi resolvida na tarefa do button :) @peixeh

2021-06-17 17:12 UTC, nicoleoliveira requested changes

2021-06-17 17:12 UTC, nicoleoliveira commented on packages/button/src/stories/best-practices.mdx
> +  alt="#PraCegoVer Três botões dispostos à direita, terciário, secundário e primário, respectivamente"
Não precisa colocar a #PraCegoVer, ela é apenas para os casos onde não conseguimos colocar o atributo "alt" nas imagens. E também é importante remover, porque o alt tem um limite de caracteres colocado por cada navegador, de normalmente 120 caracteres. 

Dai na hora de remover, é importante rever nas outras imagens também hehe

2021-06-17 18:31 UTC, edioli requested changes
- Em Boas práticas > [Interação](https://60478d54bafe87002141643c-vibchkkwnh.chromatic.com/iframe.html?id=componentes-button--visao-geral&viewMode=docs#intera%C3%A7%C3%A3o), as imagens de fazer/ não fazer estão trocadas. Está a imagem do "não fazer" no texto "fazer".
- Nas tabelas do primary e primary danger, na ultima propriedade --background-disabled está "cor da background"

2021-06-18 12:02 UTC, nicoleoliveira approved these changes

2021-06-18 12:21 UTC, edioli approved these changes

2021-06-18 13:59 UTC, merged