Textarea
animaliads/animalia-web-components pull request #22
Opened 2021-09-01 20:21 UTC by nicoleoliveira

Textarea - novo componente

Novo componente do tipo textarea.
Versão básica e unitária do componente.

Revisão, testar no:

labs do storybook
live demo
PR animalia brand: animaliads/animalia-brand#9

2021-09-02 22:22 UTC, edioli requested changes
- No estado **disabled**, por alguma razão não está pegando a cor do `--background-disabled`. Parece que a cor da variação do read-only está sobrepondo a do disabled.

- Ficou faltando a opção de incluir um placeholder

- No Safari, não está deixando redimensionar horizontalmente, como é original do componente (No Chrome está funcionando)

![text-area-safari](https://user-images.githubusercontent.com/75502935/131923396-dd88ad8e-353b-4b1b-9b95-c3251bb0a56a.gif)

2021-09-02 22:22 UTC, edioli commented on packages/textarea/src/stories/general.mdx
> +# Radio
~Radio~ Text Area

2021-09-02 22:34 UTC, edioli commented on packages/textarea/src/stories/custom-properties.mdx
> +Possui cinco estados, que se modificam de acordo com a interação do usuário, sendo eles: _Normal_, _Hover_, _Focused_ e _Disabled_.
Faltou incluir o estado _Read-only,_ 

_Normal_, _Hover_, _Focused_, _Disabled_ e _Read-only_

2021-09-02 22:37 UTC, edioli commented on packages/textarea/src/stories/code.mdx
> +
Está correto essa parte de `textarea group`? O link está levando para uma pagina inexistente.

2021-09-03 18:22 UTC, nicoleoliveira commented
> * No estado **disabled**, por alguma razão não está pegando a cor do `--background-disabled`. Parece que a cor da variação do read-only está sobrepondo a do disabled.
> * Ficou faltando a opção de incluir um placeholder
> * No Safari, não está deixando redimensionar horizontalmente, como é original do componente (No Chrome está funcionando)
> 
> ![text-area-safari](https://user-images.githubusercontent.com/75502935/131923396-dd88ad8e-353b-4b1b-9b95-c3251bb0a56a.gif)

Correção concluída!

2021-09-09 12:25 UTC, edioli approved these changes

2021-09-10 12:05 UTC, brunoromeiro approved these changes

2021-09-10 12:07 UTC, merged