feat: remove focus dos componentes quando desabilitado
animaliads/animalia-web-components pull request #27
Opened 2021-09-28 20:26 UTC by nicoleoliveira

### Remove focus dos componentes quando desabilitado

Remove dos componentes: 
- button
- checkbox
- radio

Revisão:
Pode ser testado no labs do storybook

2021-09-29 21:26 UTC, alinelariguet approved these changes, later dismissed

2021-09-30 18:46 UTC, edioli requested changes
- **Button**
Ainda está aparecendo no disabled, nas três variações (No Chrome e no Safari) 
Mas é só no clique.. Quando navega por teclado não está mais recebendo foco.

![button-disabled](https://user-images.githubusercontent.com/75502935/135511189-8de08169-08f9-469d-adf5-907607544bf2.gif)
(Chrome)

- **Checkbox**
No safari, está aparecendo o foco no disabled. No chrome não aparece
![checkbox-safari](https://user-images.githubusercontent.com/75502935/135512889-995f5e16-2a62-496b-92f2-c9b339f203a9.gif)
(Safari)

2021-10-01 13:05 UTC, nicoleoliveira commented
> * s é só no clique.. Quando navega por teclado nã

Corrigido! Obrigada :)

2021-10-01 13:25 UTC, alinelariguet approved these changes

2021-10-01 20:04 UTC, edioli approved these changes

2021-10-04 14:33 UTC, merged