feat(button): altera o tamanho do botão e refatora as propriedades
animaliads/animalia-web-components pull request #28
Opened 2021-10-06 20:17 UTC by nicoleoliveira

### Button

- Alteração do botão para 44px (mínimo)
- Alteração das propriedades do botão para um maior reaproveitamento, tanto das propriedades quanto do visual. 

#### Como revisar:

- Como visualizar como ficou o botão no labs do storybook.
- Ou testar no [demo.zip](https://github.com/animaliads/animalia-web-components/files/7296940/demo.zip)

2021-10-08 21:15 UTC, edioli requested changes

2021-10-08 21:15 UTC, edioli commented on packages/button/src/button.style.ts
>      color: var(--text-color-disabled);
No tertiary disabled, a label aplica a `--color-disabled` (igual ao secondary)

2021-10-08 21:15 UTC, edioli commented on packages/button/src/stories/custom-properties.mdx
Falta atualizar as imagens dos botões dessa seção, pois ainda está a versão com focusabled disabled

2021-10-12 12:25 UTC, nicoleoliveira commented on packages/button/src/button.style.ts
>      color: var(--text-color-disabled);
Corrigido!

2021-10-13 12:56 UTC, alinelariguet approved these changes

2021-10-13 20:38 UTC, edioli approved these changes

2021-10-13 20:43 UTC, merged