Card interativo
animaliads/animalia-web-components pull request #40
Opened 2021-12-09 14:46 UTC by gabrielibarbosa

Card interativo

Implementa interação no card, possibilitando ter os tipos: read-only, selectable e link.

Revisão, testar no:

labs do storybook
Ou instalar o pacote localmente:
npm i @animaliads/ani-card
adicionar o script instalado no html
e colocar no html

PR animalia brand: [animaliads/animalia-brand#17](https://github.com/animaliads/animalia-brand/pull/17)

2021-12-10 13:41 UTC, jribeiroo approved these changes, later dismissed

2021-12-10 13:42 UTC, rafaellmarques approved these changes, later dismissed

2021-12-13 11:49 UTC, nicoleoliveira commented
Como a maioria das pessoas que vão utilizar o card irão utilizá-los um ao lado do outro, seria interessante deixarmos isso como padrão, para que o desenvolvedor não tenha que fazer isso sempre que ele for utilizar o card.

![image](https://user-images.githubusercontent.com/17319734/145807039-4e53f2d6-c715-44f2-9d2c-4e5f374cda6d.png)

2021-12-13 20:31 UTC, nicoleoliveira commented on packages/card/src/card.ts
> +  }
é importante manter os métodos de ciclo de vida entre os primeiros

2021-12-13 20:31 UTC, nicoleoliveira commented on packages/card/src/card.ts
> +    if (this.type === 'selectable' && event.keyCode === 32) {
Agora que temos o pacote common, podemos criar um enum de KeyCode para evitar números soltos dentro do código
Sugestão:
Criar um enum dentro do common com os KeyCodes para poder utilizar dentro do componente. 

```
export enum KeyCode {
  SPACE = 32,
}

```

2021-12-13 20:31 UTC, nicoleoliveira commented on packages/card/src/card.ts
> +  private updateAttributes(attrName?, newValue?) {
Faltou colocar a tipagem no método

2021-12-14 12:46 UTC, gabrielibarbosa commented on packages/card/src/card.ts
> +  }
feito

2021-12-14 20:33 UTC, gabrielibarbosa commented
> Como a maioria das pessoas que vão utilizar o card irão utilizá-los um ao lado do outro, seria interessante deixarmos isso como padrão, para que o desenvolvedor não tenha que fazer isso sempre que ele for utilizar o card.
> 
> ![image](https://user-images.githubusercontent.com/17319734/145807039-4e53f2d6-c715-44f2-9d2c-4e5f374cda6d.png)

Resolvido!

2021-12-14 20:54 UTC, nicoleoliveira requested changes

2021-12-14 20:54 UTC, nicoleoliveira commented on packages/card/src/stories/custom-properties.mdx
> +| `--outline-color-focused` | cor do outline do focus                        | 1em (16px)              | $color-action-focus   |
A tabela desconfigurou um pouco, acho que assim pode resolver:

```suggestion
| ------------------------- | ---------------------------------------------- | ----------------------- |
| `--border-radius`         | arredondamento da borda                        | $border-radius-md       |
| `--background`            | cor de fundo do card                           | $color-neutral-light-00 |
| `--border-color`          | cor da borda                                   | $color-neutral-light-20 |
| `--border-width`          | espessura da borda                             | $border-width-sm        |
| `--padding`               | espaço interno entre a texto e a borda do card | 1em (16px)              |
| `--border-color-hover`    | cor da borda do hover                          | $color-action-hover     |
| `--shadow`                | sombra do background                           | $shadow-lg              |
| `--color-focused`         | cor principal no estado focus                  | $color-action-default |
| `--outline-color-focused` | cor do outline do focus                        | $color-action-focus   |
```

2021-12-15 12:58 UTC, jribeiroo approved these changes, later dismissed

2021-12-15 13:15 UTC, rafaellmarques submitted a review, later dismissed

2021-12-15 18:16 UTC, edioli commented
Oi! Identifiquei alguns pontos:
### Estado normal:
- A propriedade _--shadow_ está com o token incorreto. Corrigir para `shadow-md`

### Hover:
- A sombra está sumindo. Nesse estado, a sombra troca para o token `shadow-lg`, na propriedade _--shadow-hover_
![shadow-hover](https://user-images.githubusercontent.com/75502935/146240820-1d4d2c62-6b7b-4a3c-88f6-93381286c3b0.gif)

2021-12-15 18:25 UTC, edioli commented on packages/card/src/stories/card.stories.ts
> +      description: 'Indica qual é o link card irá redirecionar.',
Sugestão: _Indica para qual endereço/URL o card do tipo link irá redirecionar._

2021-12-15 18:33 UTC, edioli commented on packages/card/src/stories/custom-properties.mdx
> +| `--border-color-selected` | cor da borda quando estiver selecionado | $color-neutral-light-20  |
- `--shadow`, o valor padrão é `shadow-md`
- `--border-color-selected`, o valor padrão é `color-action-default`
- Faltou a propriedade `--shadow-hover`, com valor padrão `shadow-lg`

2021-12-16 18:13 UTC, gabrielibarbosa commented on packages/card/src/stories/card.stories.ts
> +      description: 'Indica qual é o link card irá redirecionar.',
Ajustado!

2021-12-16 18:16 UTC, gabrielibarbosa commented on packages/card/src/stories/custom-properties.mdx
> +| `--border-color-selected` | cor da borda quando estiver selecionado | $color-neutral-light-20  |
Ajustado!

2021-12-20 14:23 UTC, nicoleoliveira approved these changes

2021-12-21 12:06 UTC, merged