Icone
animaliads/animalia-web-components pull request #46
Opened 2022-02-15 18:14 UTC by gabrielibarbosa

## `<< Icon >>` - novo componente

Novo componente do tipo `<< Icon>>`

### Como revisar

- Testar no labs do storybook `<< adicione o link do labs do storybook >>`

#### Para os devs

- Clonar o repositório
- `npm i`
- `npx lerna bootstrap`
- `npx lerna run build`

Adicionar o seletor do componente no arquivo `animalia-web-components/demo/app/index.html`, da seguinte forma:

```
<ani-icon name="arrow-left"></ani-icon> >>
```

Depois execute o comando:

```
npx lerna run start
```

Que irá abrir uma janela no seu navegador com o app de demonstração do componente.

PR animalia brand: `<< colocar o link da pr do animalia-brand >>`

2022-02-16 21:46 UTC, edioli requested changes

2022-02-16 21:46 UTC, edioli commented on packages/icon/src/stories/icon.stories.ts
> +      description: 'Tamanhos do botão.',
~Tamanhos do botão~ Tamanhos do ícone

2022-02-16 21:46 UTC, edioli commented on packages/checkbox/src/checkbox.style.ts
> +  ani-icon {
O `ani-icon` ta aplicado no componente checkbox, e está ficando desalinhado.
Mas acho que essa mudança não fazia parte dessa tarefa ainda, pois precisaremos ajustar em outros componentes também, não só nesse. (Essa atualização já está no radar)

2022-02-16 21:46 UTC, edioli commented on packages/icon/src/stories/general.mdx
> +# Ícones
~Ícones~ Icon

_(pra manter o padrão do título como o nome do componente)_

2022-02-17 13:05 UTC, gabrielibarbosa commented on packages/icon/src/stories/icon.stories.ts
> +      description: 'Tamanhos do botão.',
Ajustado

2022-02-17 14:18 UTC, gabrielibarbosa commented on packages/icon/src/stories/general.mdx
> +# Ícones
Ajustado

2022-02-17 14:18 UTC, gabrielibarbosa commented on packages/checkbox/src/checkbox.style.ts
> +  ani-icon {
Ajustado

2022-02-18 19:28 UTC, edioli submitted a review, later dismissed

2022-02-18 19:28 UTC, edioli commented on packages/checkbox/src/checkbox.style.ts
>  `;
Acho que acabou removendo junto as estilizações dele, porque não está pegando a cor que estava.
<img width="155" alt="Captura de Tela 2022-02-17 às 15 32 07" src="https://user-images.githubusercontent.com/75502935/154547725-16eb1d11-700e-44c9-8b39-543b98e77ddf.png">

2022-02-24 19:39 UTC, merged